### ISSUE TITLE
Method getCurrentUrl() could be called on WebDriver implementations that does not support them

### ISSUE THREAD

**Issue by Yauhenda** [applitools/eyes.sdk.java3#147]
https://github.com/applitools/eyes.sdk.java3/blob/ea50312217ffa1d56425aab75de56d9c074a299d/eyes.selenium.java/src/main/java/com/applitools/eyes/selenium/SeleniumEyes.java#L662

since 3.154
When I try to check only region on mobile device , I have an Exception: org.openqa.selenium.WebDriverException: Method is not implemented

	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1) ~[java-client-7.1.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:289) ~[selenium-remote-driver-4.0.0-alpha-1.jar:?]
	at com.applitools.eyes.selenium.wrappers.EyesWebDriver.getCurrentUrl(EyesWebDriver.java:153) ~[eyes-selenium-java3-3.155.0.jar:?]
	at com.applitools.eyes.selenium.SeleniumEyes.check(SeleniumEyes.java:662) ~[eyes-selenium-java3-3.155.0.jar:?]

**Comment by itaibh** [comment]
Thank you for your bug report.
This has already been fixed in version 3.155.

**Comment by Yauhenda** [comment]
I'm using 3.155.0 and problem is still there.

**Comment by itaibh** [comment]
Send me your test code or a code sample that reproduces it and I'll try to
figure it out.
Sorry for your inconvenience.

Itai.
