### ISSUE TITLE
[Bug] checkWindow throws Not Implemented exception with defaultContent

### ISSUE THREAD

**Issue by mg-glb** [applitools/eyes.sdk.java3#62]
Environment:
``
dependencies {
    compile 'com.applitools:eyes-selenium-java3:RELEASE'
}
``
Appium Server Version: 1.7.2
Device API Level: 25 (Moto Z Play - Real Device - 7.1.1)
Capabilities: capabilities.setCapability("app", "http://saucelabs.com/example_files/ContactManager.apk");

When I run:

eyes.checkWindow("Contact list!");

I get the following stacktrace:

===================================================================
Apr 21, 2018 10:09:37 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'AR-IT05414', ip: '192.168.26.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: http://saucelabs.com/exampl..., appActivity: com.example.android.contact..., appPackage: com.example.android.contact..., appWaitActivity: com.example.android.contact..., appWaitPackage: com.example.android.contact..., databaseEnabled: false, desired: {app: http://saucelabs.com/exampl..., deviceName: ZY223L7LMS, platformName: android, platformVersion: 7.1.1}, deviceManufacturer: motorola, deviceModel: XT1635-02, deviceName: ZY223L7LMS, deviceScreenSize: 1080x1920, deviceUDID: ZY223L7LMS, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, platform: LINUX, platformName: LINUX, platformVersion: 7.1.1, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
Session ID: 0c8c5325-ccc2-46be-b68c-72046c6017fc
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:129)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.defaultContent(RemoteWebDriver.java:921)
	at com.applitools.eyes.selenium.wrappers.EyesTargetLocator.defaultContent(EyesTargetLocator.java:228)
	at com.applitools.eyes.selenium.Eyes.check(Eyes.java:663)
	at com.applitools.eyes.selenium.Eyes.checkWindow(Eyes.java:375)
	at com.applitools.eyes.selenium.Eyes.checkWindow(Eyes.java:366)
	at io.mgigena.Main.main(Main.java:32)

Process finished with exit code 1

===================================================================

And the following is logged by Appium server:

===================================================================
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["return navigator.userAgent",[],"0c8c5325-ccc2-46be-b68c-72046c6017fc"]
[HTTP] <-- POST /wd/hub/session/0c8c5325-ccc2-46be-b68c-72046c6017fc/execute 501 4 ms - 112
[HTTP] --> POST /wd/hub/session/0c8c5325-ccc2-46be-b68c-72046c6017fc/frame {"id":null}
[debug] [MJSONWP] Calling AppiumDriver.setFrame() with args: [null,"0c8c5325-ccc2-46be-b68c-72046c6017fc"]
[HTTP] <-- POST /wd/hub/session/0c8c5325-ccc2-46be-b68c-72046c6017fc/frame 501 4 ms - 122

===================================================================

Apparently, a Not Implemented exception is thrown by the line:
``
this.targetLocator.defaultContent();
``
at com.applitools.eyes.selenium.wrappers.EyesTargetLocator.defaultContent(EyesTargetLocator.java:228)

My full code is a copy of https://applitools.com/resources/tutorial/appium/native_java#step-2 (for the real android device).

I haven't tried with other devices yet.

Thank you very much!

**Comment by mg-glb** [comment]
The version of the repo is 3.32.1

**Comment by danielputerman** [comment]
Hi, fixed in https://github.com/applitools/eyes.sdk.java3/releases/tag/v3.35

**Comment by danielputerman** [comment]
And thanks for the feedback of course :)

**Comment by mg-glb** [comment]
Thank you very much!
