### ISSUE TITLE
[Bug] checkWindow throws call function result missing 'value'  with setPosition

### ISSUE THREAD

**Issue by mg-glb** [applitools/eyes.sdk.java3#63]
Environment:
``
dependencies {
    compile 'com.applitools:eyes-selenium-java3:3.32.1'
}
``
Appium Server Version: 1.7.2
Device API Level: 25 (Moto Z Play - Real Device - 7.1.1)

My code is the same as defined in https://applitools.com/resources/tutorial/appium/java

When I run:
``
eyes.checkWindow("Hello!");
``
I get the following stacktrace:

===================================================================

Apr 22, 2018 1:01:25 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.106)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'AR-IT05414', ip: '192.168.26.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {browserName: chrome, databaseEnabled: false, desired: {browserName: chrome, deviceName: ZY223L7LMS, platformName: android, platformVersion: 7.1.1}, deviceManufacturer: motorola, deviceModel: XT1635-02, deviceName: ZY223L7LMS, deviceScreenSize: 1080x1920, deviceUDID: ZY223L7LMS, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, platform: LINUX, platformName: LINUX, platformVersion: 7.1.1, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
Session ID: 023f0e96-311e-4c71-b46d-4cbb9419d49d
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:482)
	at com.applitools.eyes.selenium.wrappers.EyesWebDriver.executeScript(EyesWebDriver.java:337)
	at com.applitools.eyes.selenium.SeleniumJavaScriptExecutor.executeScript(SeleniumJavaScriptExecutor.java:16)
	at com.applitools.eyes.selenium.EyesSeleniumUtils.setCurrentScrollPosition(EyesSeleniumUtils.java:241)
	at com.applitools.eyes.selenium.positioning.ScrollPositionProvider.setPosition(ScrollPositionProvider.java:48)
	at com.applitools.eyes.selenium.Eyes.check(Eyes.java:665)
	at com.applitools.eyes.selenium.Eyes.checkWindow(Eyes.java:375)
	at io.mgigena.WebTest.main(WebTest.java:37)

Process finished with exit code 1

===================================================================

Apparently, the exception arises when trying to execute the script ``window.scrollTo(0,0)`` on the browser.

Moreover, this issue could be related to https://stackoverflow.com/questions/48609069/org-openqa-selenium-webdriverexception-unknown-error-call-function-result-miss

**Comment by danielputerman** [comment]
Fixed in version 3.35: https://github.com/applitools/eyes.sdk.java3/releases/tag/v3.35
