### ISSUE TITLE
Unhandled endpoint

### ISSUE THREAD

**Issue by aljones15** [applitools/eyes.sdk.java3#69]
org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/05E12F20-DB86-4C5E-82B4-9C9F14A1E884/frame -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/05E12F20-DB86-4C5E-82B4-9C9F14A1E884/frame"
    );
}

    BaseTest.eyes.open(BaseTest.driver, "test app", "LoginTest");

this succeeds, but

    BaseTest.eyes.checkWindow("Get Started");

fails.

appium server 1.8.1
appium java client 

<dependency>
        <groupId>io.appium</groupId>
        <artifactId>java-client</artifactId>
        <version>6.0.0</version>
        <exclusions>
            <exclusion>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

**Comment by aljones15** [comment]
org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/877C0931-31B7-4A52-9999-1ACDCDB8DF47/frame -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/877C0931-31B7-4A52-9999-1ACDCDB8DF47/frame"
    );
}
Command duration or timeout: 0 milliseconds
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'Andrews-MacBook-Pro.local', ip: 'fe80:0:0:0:10ac:61c2:7197:39c0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_121'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/andrewjones/Programs..., automationName: XCUITest, browserName: , databaseEnabled: false, deviceName: iPhone X, javascriptEnabled: true, launchTimeout: 820000, locationContextEnabled: false, networkConnectionEnabled: false, noReset: false, platform: MAC, platformName: MAC, platformVersion: 11.2, shouldUseSingletonTestManager: true, showIOSLog: false, showXcodeLog: true, takesScreenshot: true, udid: 3D87EE73-7C68-4932-B815-08B..., useJSONSource: false, useNewWDA: true, webStorageEnabled: false}
Session ID: 078a4abb-ba9e-4e56-aa05-3f99f63dd7c1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:129)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.defaultContent(RemoteWebDriver.java:913)
	at com.applitools.eyes.selenium.wrappers.EyesTargetLocator.defaultContent(EyesTargetLocator.java:228)
	at com.applitools.eyes.selenium.Eyes.check(Eyes.java:663)
	at com.applitools.eyes.selenium.Eyes.checkWindow(Eyes.java:375)
	at tests.LoginTest.validLoginTest(LoginTest.java:20)


Results :

Failed tests:   validLoginTest(tests.LoginTest): Unhandled endpoint: /session/877C0931-31B7-4A52-9999-1ACDCDB8DF47/frame -- http://localhost:8100/ with parameters {(..)
